# Generated by Django 5.1.7 on 2025-03-16 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='job_title',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='qr_code',
            field=models.CharField(db_index=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['attendee', 'timestamp'], name='qr_attendan_attende_b7a4cf_idx'),
        ),
        migrations.AddIndex(
            model_name='attendee',
            index=models.Index(fields=['name', 'job_title'], name='qr_attendan_name_6520ed_idx'),
        ),
    ]
